### ISSUE TITLE
problem loading resource from url

### ISSUE THREAD

**Issue by runseb** [mission-liao/pyswagger#34]
Hi, I just tried your package and I am having an issue loading my swagger resource file.

I tried:

    >>> app = SwaggerApp.create('http://10.0.0.10:8080/swaggerapi/api/v1beta2')

As you can see it is not served from a swagger.json file but returned directly from a get request as json.

The SwaggerApp.create returns a 404 Not Found.

I tried saving it to a json file, but ran into other type of issues...

**Comment by mission-liao** [comment]
Hi, thanks for reporting issues. I added a test to try the url you used, and utilized httpretty to mock the result. It seems work just fine, and the url past into urllib is 'http://10.0.0.10:8080/swaggerapi/api/v1beta2', not touched at all. Maybe I need more info on this part.

On the other hand, could you also provide more details about loading from local? It's frustrated when trying this library and failing at loading step. Thanks for your help.

**Comment by runseb** [comment]
Here is a link to the file live:

http://people.apache.org/~sebgoa/swagger.json

I will try it again

**Comment by runseb** [comment]
yeah the getter does not quite work:

    >>> app = SwaggerApp.create('http://people.apache.org/~sebgoa/swagger.json')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-    packages/pyswagger/core.py", line 320, in create
        app = kls.load(url)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyswagger/core.py", line 260, in load
        app._load_obj(url, getter, parser)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyswagger/core.py", line 165, in _load_obj
        ctx.parse(getter, obj)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyswagger/spec/v1_2/parser.py", line 167, in parse
        for obj, name in getter:
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/six.py", line 535, in next
        return type(self).__next__(self)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyswagger/getter.py", line 26, in __next__
        obj = self.load(path)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyswagger/getter.py", line 132, in load
        f = six.moves.urllib.request.urlopen(path)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
        return opener.open(url, data, timeout)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
        response = meth(req, response)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
        'http', request, response, code, msg, hdrs)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
        return self._call_chain(*args)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
        result = func(*args)
      File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
        raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
    urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by mission-liao** [comment]
Hi, thanks for providing the url, that's helpful.

When pyswagger tried to load from http://people.apache.org/~sebgoa/swagger.json, that file was loaded successfully, and its version of Swagger is 1.2, therefore, pyswagger would try to seek other resource files, they are [API Declaration](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md).

Therefore, pyswagger tried to load from http://people.apache.org/~sebgoa/swagger.json/api/v1beta2/bindings, and there is nothing.

I check http://people.apache.org/~sebgoa/swagger.json and found it's neither a valid document of Swagger 1.2 or 2.0. Its file structure looks like 2.0 but all its terms and objects are 1.2.

The file structure of Swagger 1.2 is
- [Resource Listing](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#51-resource-listing)
  - [API Declaration](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#52-api-declaration)

The process to load a Swagger document in 1.2 is loading __Resource Listing__ first, check the relative path of each __API Declaration__, and then load each API correspondingly.

My suggestion on that document is migrating that one to Swagger 2.0, refer to [here](https://github.com/swagger-api/swagger-spec/wiki/Swagger-1.2-to-2.0-Migration-Guide).

**Comment by runseb** [comment]
thanks for the info and looking into it.

That's the api from https://github.com/GoogleCloudPlatform/kubernetes

I will file an issue there :)
