### ISSUE TITLE
ValueError: Unknown object to dump: float

### ISSUE THREAD

**Issue by torwald-sergesson** [mission-liao/pyswagger#92]
I have this code in my swagger file in definitions section:

```
definitions:
  Location:
    title: Location
    description: 'Location coordinates'
    type: object
    properties:
      lon:
        type: number
        description: Longitude
        example: 86.12
      lat:
        type: number
        description: Latitude
        example: 56.123
    required:
      - lon
      - lat
```

When I try to dump it, I got this ValueError.

```
>>>app = App._create_('swagger.yaml')
>>> app.root.dump()
Traceback (most recent call last):
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-99ddff4bc766>", line 1, in <module>
    self.app.root.dump()
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 420, in dump
    d = _dump_(v)
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 402, in _dump_
    ret[k] = _dump_(v)
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 410, in _dump_
    return obj.dump()
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 420, in dump
    d = _dump_(v)
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 402, in _dump_
    ret[k] = _dump_(v)
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 410, in _dump_
    return obj.dump()
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 420, in dump
    d = _dump_(v)
  File "/home/torwald/.venv/anyevent__backend/lib/python3.5/site-packages/pyswagger/spec/base.py", line 414, in _dump_
    raise ValueError('Unknown object to dump: {0}'.format(obj.__class__.__name__))
ValueError: Unknown object to dump: float
```

**Comment by mission-liao** [comment]
the fix is included in v0.8.25, thanks for contributing and feel free to reopen it when not work.
